; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

lib_deps =
   stevemarple/SoftWire@^2.0.10

upload_protocol = stlink
debug_tool = stlink

upload_flags = -c set CPUTAPID 0x2ba01477
debug_speed = 500
debug_server =
  ${platformio.packages_dir}/tool-openocd/bin/openocd
  -s ${platformio.packages_dir}/tool-openocd/openocd/scripts
  -f interface/stlink.cfg
  -c "transport select hla_swd"
  -c "set CPUTAPID 0x2ba01477"
  -f target/stm32f1x.cfg
  -c "reset_config none"
  -c "gdb_port pipe; tcl_port disabled; telnet_port disabled"


build_flags =
   -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
   -D USBCON
   -D USBD_VID=0x0483
   -D USBD_PID=0x5740
   -D USB_MANUFACTURER="jgdo"
   -D USB_PRODUCT="\"BLUEPILL_F103C8\""
   -D HAL_PCD_MODULE_ENABLED
   -D HAVE_HWSERIAL2
   -D HAVE_HWSERIAL3

monitor_port = /dev/ttyACM0
